name: project
description: "Flutter app: список любимых фильмов"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Управление состоянием (Bloc / Cubit)
  flutter_bloc: ^8.1.3

  # Хранение данных 
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Пути к файлам (нужно для картинок)
  path_provider: ^2.1.2

  # Сохранение темы 
  shared_preferences: ^2.2.2

  # Выбор изображений 
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Генерация Hive адаптеров
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
